<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>Galeria de Veículos Militares</title>
  <style>
    body {
      margin: 0;
      font-family: Arial, sans-serif;
      background-color: #1e1e1e;
      color: white;
      padding: 20px;
    }

    h1 {
      text-align: center;
      color: #c0ffb3;
    }

    .galeria {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 20px;
      margin-top: 30px;
    }

    .item {
      background-color: #2e2e2e;
      padding: 15px;
      border-radius: 10px;
      text-align: center;
      transition: transform 0.2s;
      cursor: pointer;
    }

    .item:hover {
      transform: scale(1.05);
      background-color: #3e3e3e;
    }

    .item img {
      width: 100%;
      height: 250px;
      object-fit: cover;
      border-radius: 8px;
    }

    .item h3 {
      margin: 10px 0 0;
    }
  </style>
</head>
<body>
  <h1>Galeria de Veículos Militares</h1>

  <div class="galeria">
    <div class="item" onclick="abrirModelo('leopard')">
      <img src="img/leopard.png" alt="Leopard 1A5">
      <h3>LEOPARD 1A5 TORC 30 BR</h3>
    </div>
    <div class="item" onclick="abrirModelo('guarani')">
      <img src="img/guarani.png" alt="VBTP Guarani">
      <h3>VBTP Guarani</h3>
    </div>
    <div class="item" onclick="abrirModelo('urutu')">
      <img src="img/urutu.png" alt="VBR Urutu">
      <h3>VBR Urutu</h3>
    </div>
    <div class="item" onclick="abrirModelo('nauru')">
        <img src="img/nauru1000c.png" alt="VBR Urutu">
        <h3>Drone NAURU</h3>
      </div>
      <div class="item" onclick="abrirModelo('guaicuru')">
        <img src="img/guaicuru.png" alt="VBR Urutu">
        <h3>VBMT-4X4 GUAICURU BR</h3>
      </div>
    <!-- Adicione mais aqui -->
  </div>

  <script>
    function abrirModelo(modelo) {
      window.location.href = `modelo.html?modelo=${modelo}`;
    }
  </script>
</body>
</html>
